name: Testing App
on: push
jobs:
  test:
    runs-on: windows-latest
      steps:
        - name: Getting code
          uses: actions/checkout@v4
        - name: Install Dependencies
          run: npm ci
        - name: Test App
          run: npm run test